### ISSUE TITLE
Should we allow for varying AudioParam values?

### ISSUE THREAD

**Issue by chihuahua** [google/audion#18]
I think it's a tradeoff. I'm leaning towards showing realtime values, but not letting the user vary them.

Varying AudioParam's is neat - it can be useful to experiment / tinker, but the feature implies maintaining a reference to nodes, preventing GC. Blocking a source node from getting GCed could prevent its entire AudioBuffer from getting GCed ... which might be bad?

If we just let the user view AudioParam values in realtime, we might not need to maintain references to the nodes. We would just I think override the getters and setters of the value properties to issue a message when values change, maybe by defining a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

**Comment by rtoy** [comment]
If this is the WebAudio **Inspector**, I would so, no, don't allow changes.  If it's more like a debugger than an inspector, go for it.  Allow modification of anything that is sensibly modifiable! (And maybe change the name to WebAudio **Debugger** when you do this.)

**Comment by chihuahua** [comment]
Inspector does imply a passive extension. It may be worth noting that users can already obtain references to nodes via the global `__node__` method. And the modify the node at will of course.

**Comment by chihuahua** [comment]
It seems like we're converging on not allowing the UI to vary params. If no one opposes, how about we just close this bug til someone reopens it.
