### ISSUE TITLE
Connection edges are drawn incorrectly on M57/M58.

### ISSUE THREAD

**Issue by hoch** [google/audion#41]
All the ports are placed in the left-top corner of the node rect.

![screen shot 2017-03-08 at 2 40 35 pm](https://cloud.githubusercontent.com/assets/676891/23727520/3ffa2452-040d-11e7-8c86-e90b7706b212.png)

I don't think this is our bug though. Something must have been changed in SVG or Canvas.

**Comment by chihuahua** [comment]
Resolving this issue because bda0b5a24d88e4dc9f9503cc4fed84256ae51a16 removed the patch.
