### ISSUE TITLE
BaseAudioContext.createSpatialPanner should not be defined.

### ISSUE THREAD

**Issue by rtoy** [google/audion#65]
`BaseAudioContext.prototype` includes `createSpatialPanner`.  This is incorrect; there is no such property defined for `BaseAudioContext`.

Wrapping of properties should be more careful and only create wrappers for properties that actually exist in a `BaseAudioContext`.

**Comment by chihuahua** [comment]
Thanks for the notice! I just removed `createSpatialPanner`. And the `SpatialPannerNode` (commit ac7465f0be7b3364297bb9ba6e46bbf9424d9a69).
