### ISSUE TITLE
Publish audion to addons.mozilla.org

### ISSUE THREAD

**Issue by Xiphoseer** [google/audion#94]
I was investigating some weird audio behavior in chrome when I stumbled across the WebAudio roadmap for chromium dev tools. This mentiond creating this extension in part to achieve feature-parity with the WebAudio Editor in Firefox. [This MDN Page](https://developer.mozilla.org/en-US/docs/Tools/Web_Audio_Editor) was linked in the roadmap, which says that the feature is deprected by now and the [List of deprecated tools in FF](https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools) says that this was removed in [Bug 1403944](https://bugzilla.mozilla.org/show_bug.cgi?id=1403944) because `audion` works well enough in Firefox and it was no longer reasonable to maintain a browser feature based on legacy technology (XUL) for the same purpose.

Now the issue is, that this extension is only released in the chrome web store which can't be used to load it into firefox. In the interest of cross-browser collaboration and compatibility, would it be possible to release `audion` as-is on https://addons.mozilla.org?

**Comment by devviktoria** [comment]
Hi,
there is an extension for it already: Web Audio Inspector by Metroite. You can install the extension from here:
https://addons.mozilla.org/en-US/firefox/addon/web-audio-inspector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by hoch** [comment]
Thanks for the information. Closing.
